### ISSUE TITLE
Handing over the project 

### ISSUE THREAD

**Issue by KacperSzmitko** [antmicro-labs/image-recognizer#7]
At the beginning of next week, we would be ready to hand over the project. What should this process look like?

**Comment by KacperSzmitko** [comment]
@tgorochowik

**Comment by tgorochowik** [comment]
Please make sure it has a github actions CI which shows how your code can be used (with examples).
Also make sure the README is complete, it should explain how it works and how to use it (so some overlap with the CI here).

Please let me know once everything is ready

**Comment by KacperSzmitko** [comment]
@tgorochowik I thnik we done everythiing you asked for. Can you look at this? 
How will it look like to pass the project? Because the grade for the subject must be given by 26.01

**Comment by tgorochowik** [comment]
Hi, please make sure the README has some runnable examples (with some inputs you know work well, and maybe some that are problematic).

Please also make sure it includes some information about the model, how to train it and how to get the dataset (if it's generated, the scripts need to be included in the repo)

**Comment by tgorochowik** [comment]
Also, please put the models here: https://github.com/antmicro-labs/image-recognizer-models instead of uploading them to google drive. This repo can be then used as a submodule to your project.
You can use git LFS to make it more efficient.

**Comment by KacperSzmitko** [comment]
Models are too big to upload them to github. That's why we used gd.

**Comment by KacperSzmitko** [comment]
@tgorochowik I think everything is here now

**Comment by glatosinski** [comment]
Hi, I think it'd be good to also add notebooks from Google Colab for training the models to the repository, e.g. `notebooks/` directory.

**Comment by KacperSzmitko** [comment]
@glatosinski Okay added this

**Comment by KacperSzmitko** [comment]
@tgorochowik So what about this? Because as i said the grade for the subject must be given by 26.01. So what should we do now?

**Comment by glatosinski** [comment]
Some final things from me:

* You could fix the issues with the CI so it ends green
* You could add possibility to print all data about image - its format, format confidence, resolution, resolution confidence, so we don't need to go through multiple calls
* You could probably enable memory growth for TensorFlow so it does not consume all GPU RAM

**Comment by KacperSzmitko** [comment]
We cannot fix CI beacuse we exceeded LFS bandwidth

**Comment by glatosinski** [comment]
Ok, so let's leave CI issue now.

**Comment by glatosinski** [comment]
As for the grade, we are in contact with your teacher regarding the delivery of the task

**Comment by kgugala** [comment]
> We cannot fix CI beacuse we exceeded LFS bandwidth

please retry pushing the models, you should be able to do it now
